export const DASHBOARD_CARDS_INFO_REQUEST = 'DASHBOARD_CARDS_INFO_REQUEST'
export const DASHBOARD_CARDS_INFO_RESET = 'DASHBOARD_CARDS_INFO_RESET'

export const DASHBOARD_WEEKLY_REQUEST = 'DASHBOARD_WEEKLY_REQUEST'
export const DASHBOARD_WEEKLY_SUCCESS = 'DASHBOARD_WEEKLY_SUCCESS'
export const DASHBOARD_WEEKLY_FAIL = 'DASHBOARD_WEEKLY_FAIL'
export const DASHBOARD_WEEKLY_RESET = 'DASHBOARD_WEEKLY_RESET'