export const DASHBOARD_CARDS_INFO_REQUEST = 'DASHBOARD_CARDS_INFO_REQUEST'
export const DASHBOARD_CARDS_INFO_SUCCESS = 'DASHBOARD_CARDS_INFO_SUCCESS'
export const DASHBOARD_CARDS_INFO_FAIL = 'DASHBOARD_CARDS_INFO_FAIL'