export const DRAFT_CREATE_REQUEST = 'DRAFT_CREATE_REQUEST'
export const DRAFT_CREATE_SUCCESS = 'DRAFT_CREATE_SUCCESS'
export const DRAFT_CREATE_FAIL = 'DRAFT_CREATE_FAIL'
export const DRAFT_CREATE_RESET = 'DRAFT_CREATE_RESET'

export const DRAFT_DETAIL_REQUEST = 'DRAFT_DETAIL_REQUEST'
export const DRAFT_DETAIL_SUCCESS = 'DRAFT_DETAIL_SUCCESS'
export const DRAFT_DETAIL_FAIL = 'DRAFT_DETAIL_FAIL'
export const DRAFT_DETAIL_RESET = 'DRAFT_DETAIL_RESET'

export const DRAFT_UPDATE_REQUEST = 'DRAFT_UPDATE_REQUEST'
export const DRAFT_UPDATE_SUCCESS = 'DRAFT_UPDATE_SUCCESS'
export const DRAFT_UPDATE_FAIL = 'DRAFT_UPDATE_FAIL'
export const DRAFT_UPDATE_RESET = 'DRAFT_UPDATE_RESET'

export const DRAFT_LIST_REQUEST = 'DRAFT_LIST_REQUEST'
export const DRAFT_LIST_SUCCESS = 'DRAFT_LIST_SUCCESS'
export const DRAFT_LIST_FAIL = 'DRAFT_LIST_FAIL'

export const DRAFT_REMOVE_REQUEST = 'DRAFT_REMOVE_REQUEST'
export const DRAFT_REMOVE_SUCCESS = 'DRAFT_REMOVE_SUCCESS'
export const DRAFT_REMOVE_FAIL = 'DRAFT_REMOVE_FAIL'
export const DRAFT_REMOVE_RESET = 'DRAFT_REMOVE_RESET'